name: firebase_note_one
description: For spesific platform

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # design
  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_database: ^9.1.0
  firebase_storage: ^10.3.4

  # storage
  shared_preferences: ^2.0.15

  # image
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
